# Generated by Django 5.0.6 on 2024-07-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='networkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField()),
                ('Index', models.IntegerField()),
                ('SourceIP', models.CharField(max_length=100)),
                ('DestinationIP', models.CharField(max_length=100)),
                ('DataLoad', models.IntegerField(blank=True)),
            ],
        ),
    ]
