# Generated by Django 5.0.6 on 2024-07-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_networkdata_destinationip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdata',
            name='DataLoad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkdata',
            name='DestinationIP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkdata',
            name='Index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkdata',
            name='SourceIP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkdata',
            name='TimeStamp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
