# Generated by Django 3.2.12 on 2024-07-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='room',
            new_name='roomTest',
        ),
    ]
