# Generated by Django 4.1.13 on 2024-07-15 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_room_roomtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='roomTest',
        ),
        migrations.AddField(
            model_name='networkdata',
            name='DestinationPORT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkdata',
            name='PackageType',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='networkdata',
            name='SourcePOST',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkdata',
            name='DestinationIP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkdata',
            name='SourceIP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkdata',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 15, 22, 3, 49, 807972)),
        ),
    ]
